/* Cipher Atelier: precise privacy statements matched to the current static implementation. */
import PublicPage from "@/components/PublicPage";

const statements = [
  [
    "Passwords",
    "Passwords entered for analysis and passwords generated by the workbench remain in browser memory for the active session. Vaultloom does not submit them to a password-analysis API, store them in a database, or write them to browser storage.",
  ],
  [
    "Clipboard",
    "The app writes a generated password to the clipboard only after you choose Copy. Clipboard managers, browser extensions, and the operating system may handle clipboard data independently of this website.",
  ],
  [
    "Cookies and analytics",
    "The current application does not set its own cookies and does not include an application analytics script. The site host or your browser may still process ordinary technical request data under their own policies.",
  ],
  [
    "Support links",
    "If you follow the repository or issue links, GitHub processes information under GitHub’s own policies. Do not publish live credentials or personal data in an issue.",
  ],
  [
    "Changes",
    "If the product adds accounts, a contact form, analytics, or any server-side feature, this notice will be updated before that collection is enabled.",
  ],
] as const;

export default function Privacy() {
  return (
    <PublicPage
      eyebrow="Privacy notice"
      ledger="Record 04"
      title="Your password is not our data."
      lede="This notice describes the current local-first Vaultloom workbench. Last updated August 25, 2026."
    >
      <div className="max-w-3xl">
        <p className="text-sm leading-7 text-black/70">
          Vaultloom is designed so the central secret—the password—stays in the
          active browser session. This notice is specific to the published
          workbench and should be read alongside the policies of the browser,
          device, host, and external services you choose to use.
        </p>
        <div className="mt-9 divide-y divide-black/10 border-y border-black/10">
          {statements.map(([title, copy], index) => (
            <article
              className="grid gap-3 py-6 sm:grid-cols-[120px_1fr]"
              key={title}
            >
              <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#275df5]">
                {String(index + 1).padStart(2, "0")} · {title}
              </span>
              <p className="text-sm leading-7 text-black/70">{copy}</p>
            </article>
          ))}
        </div>
      </div>
    </PublicPage>
  );
}
